import type { FuelType } from '@/types/database'

export interface EVPreset {
  id: string
  brand: string
  model: string
  variant: string
  fuel_type: FuelType
  power_kw: number
  battery_kwh: number
  consumption: number // kWh/100km
  year: number
  // Review fields
  rating: number // 1-10 scale
  pros: string[] // 3-5 pros
  cons: string[] // 3-5 cons
  reviewUrl?: string // Optional link to ADAC/EFAHRER review
}

// Electric Vehicles available in Germany/Europe
// Data sourced from ev-database.org and official manufacturer specs
export const EV_PRESETS: EVPreset[] = [
  // ============================================
  // TESLA
  // ============================================

  // Tesla Model 3
  {
    id: 'tesla-model-3-rwd-2024',
    brand: 'Tesla',
    model: 'Model 3',
    variant: 'RWD 60 kWh',
    fuel_type: 'bev',
    power_kw: 208,
    battery_kwh: 60,
    consumption: 14.0,
    year: 2024,
    rating: 8.5,
    pros: [
      'Excellent efficiency and range',
      'Fast Supercharger network access',
      'Strong performance and handling',
      'Regular OTA software updates',
    ],
    cons: [
      'Polarizing interior minimalism',
      'Build quality inconsistencies',
      'Limited service center availability',
      'No Apple CarPlay/Android Auto',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/tesla/model-3/',
  },
  {
    id: 'tesla-model-3-rwd-2025',
    brand: 'Tesla',
    model: 'Model 3',
    variant: 'RWD 62.5 kWh (MY25)',
    fuel_type: 'bev',
    power_kw: 208,
    battery_kwh: 62.5,
    consumption: 13.9,
    year: 2025,
    rating: 8.6,
    pros: [
      'Best-in-class efficiency',
      'Improved interior quality over predecessor',
      'Fast Supercharger network access',
      'Regular OTA software updates',
    ],
    cons: [
      'Polarizing interior minimalism',
      'No Apple CarPlay/Android Auto',
      'Limited service center availability',
      'Stalk-less design takes adjustment',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/tesla/model-3/',
  },
  {
    id: 'tesla-model-3-lr-2024',
    brand: 'Tesla',
    model: 'Model 3',
    variant: 'Long Range AWD 75 kWh',
    fuel_type: 'bev',
    power_kw: 366,
    battery_kwh: 75,
    consumption: 14.7,
    year: 2024,
    rating: 8.7,
    pros: [
      'Excellent real-world range (550+ km)',
      'Fast Supercharger network access',
      'AWD provides great traction',
      'Strong performance and handling',
    ],
    cons: [
      'Polarizing interior minimalism',
      'Premium price over RWD variant',
      'Limited service center availability',
      'No Apple CarPlay/Android Auto',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/tesla/model-3/',
  },
  {
    id: 'tesla-model-3-performance-2024',
    brand: 'Tesla',
    model: 'Model 3',
    variant: 'Performance 75 kWh',
    fuel_type: 'bev',
    power_kw: 460,
    battery_kwh: 75,
    consumption: 15.3,
    year: 2024,
    rating: 8.8,
    pros: [
      'Exhilarating acceleration (3.1s 0-100)',
      'Track-capable handling',
      'Fast Supercharger network access',
      'Still efficient for a performance car',
    ],
    cons: [
      'Firm ride quality',
      'Higher energy consumption',
      'Expensive compared to base Model 3',
      'No Apple CarPlay/Android Auto',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/tesla/model-3/',
  },

  // Tesla Model Y
  {
    id: 'tesla-model-y-rwd-2024',
    brand: 'Tesla',
    model: 'Model Y',
    variant: 'RWD 60 kWh',
    fuel_type: 'bev',
    power_kw: 220,
    battery_kwh: 60,
    consumption: 15.7,
    year: 2024,
    rating: 8.3,
    pros: [
      'Spacious interior with good cargo space',
      'Fast Supercharger network access',
      'Good real-world range',
      'Strong resale value',
    ],
    cons: [
      'Firm ride quality',
      'Interior feels sparse for the price',
      'Limited service center availability',
      'No Apple CarPlay/Android Auto',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/tesla/model-y/',
  },
  {
    id: 'tesla-model-y-lr-rwd-2024',
    brand: 'Tesla',
    model: 'Model Y',
    variant: 'Long Range RWD 75 kWh',
    fuel_type: 'bev',
    power_kw: 220,
    battery_kwh: 75,
    consumption: 15.2,
    year: 2024,
    rating: 8.5,
    pros: [
      'Excellent range for an SUV (500+ km)',
      'Spacious interior with good cargo space',
      'Fast Supercharger network access',
      'Efficient RWD drivetrain',
    ],
    cons: [
      'Firm ride quality',
      'Interior feels sparse for the price',
      'Limited service center availability',
      'No Apple CarPlay/Android Auto',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/tesla/model-y/',
  },
  {
    id: 'tesla-model-y-lr-awd-2025',
    brand: 'Tesla',
    model: 'Model Y',
    variant: 'Long Range AWD 75 kWh (Juniper)',
    fuel_type: 'bev',
    power_kw: 340,
    battery_kwh: 75,
    consumption: 15.5,
    year: 2025,
    rating: 8.7,
    pros: [
      'Refreshed design with improved interior',
      'AWD provides excellent traction',
      'New light bar design front and rear',
      'Improved NVH and ride comfort',
    ],
    cons: [
      'Higher price than predecessor',
      'Controversial front-end styling',
      'No Apple CarPlay/Android Auto',
      'Limited service center availability',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/tesla/model-y/',
  },
  {
    id: 'tesla-model-y-performance-2024',
    brand: 'Tesla',
    model: 'Model Y',
    variant: 'Performance 75 kWh',
    fuel_type: 'bev',
    power_kw: 393,
    battery_kwh: 75,
    consumption: 16.9,
    year: 2024,
    rating: 8.6,
    pros: [
      'Fast acceleration (3.7s 0-100)',
      'Sporty handling for an SUV',
      'Fast Supercharger network access',
      'Practical performance car',
    ],
    cons: [
      'Firm ride quality',
      'Higher energy consumption',
      'Expensive compared to base Model Y',
      'No Apple CarPlay/Android Auto',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/tesla/model-y/',
  },

  // Tesla Model S
  {
    id: 'tesla-model-s-2024',
    brand: 'Tesla',
    model: 'Model S',
    variant: 'Dual Motor AWD 95 kWh',
    fuel_type: 'bev',
    power_kw: 493,
    battery_kwh: 95,
    consumption: 17.6,
    year: 2024,
    rating: 8.4,
    pros: [
      'Excellent range (600+ km)',
      'Luxurious and spacious interior',
      'Strong performance',
      'Fast Supercharger network access',
    ],
    cons: [
      'Very expensive',
      'Yoke steering wheel controversial',
      'Limited service center availability',
      'Complex infotainment system',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/tesla/model-s/',
  },
  {
    id: 'tesla-model-s-plaid-2024',
    brand: 'Tesla',
    model: 'Model S',
    variant: 'Plaid 95 kWh',
    fuel_type: 'bev',
    power_kw: 760,
    battery_kwh: 95,
    consumption: 18.5,
    year: 2024,
    rating: 8.7,
    pros: [
      'Insane acceleration (2.1s 0-100)',
      'Excellent range despite power',
      'Luxurious interior',
      'Tech showcase vehicle',
    ],
    cons: [
      'Extremely expensive',
      'Yoke steering wheel controversial',
      'Overkill for daily driving',
      'Limited service center availability',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/tesla/model-s/',
  },

  // Tesla Model X
  {
    id: 'tesla-model-x-2024',
    brand: 'Tesla',
    model: 'Model X',
    variant: 'Dual Motor AWD 95 kWh',
    fuel_type: 'bev',
    power_kw: 493,
    battery_kwh: 95,
    consumption: 19.2,
    year: 2024,
    rating: 8.2,
    pros: [
      'Unique falcon wing doors',
      'Spacious 6 or 7 seat configuration',
      'Strong performance for an SUV',
      'Fast Supercharger network access',
    ],
    cons: [
      'Very expensive',
      'Falcon wing doors can be problematic',
      'High energy consumption',
      'Limited service center availability',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/tesla/model-x/',
  },
  {
    id: 'tesla-model-x-plaid-2024',
    brand: 'Tesla',
    model: 'Model X',
    variant: 'Plaid 95 kWh',
    fuel_type: 'bev',
    power_kw: 760,
    battery_kwh: 95,
    consumption: 20.0,
    year: 2024,
    rating: 8.5,
    pros: [
      'Supercar acceleration in SUV body',
      'Unique falcon wing doors',
      'Spacious 6 or 7 seat configuration',
      'Fast Supercharger network access',
    ],
    cons: [
      'Extremely expensive',
      'Very high energy consumption',
      'Falcon wing doors can be problematic',
      'Limited service center availability',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/tesla/model-x/',
  },

  // ============================================
  // VOLKSWAGEN ID SERIES
  // ============================================

  // VW ID.3
  {
    id: 'vw-id3-pure-2024',
    brand: 'Volkswagen',
    model: 'ID.3',
    variant: 'Pure 55 kWh',
    fuel_type: 'bev',
    power_kw: 125,
    battery_kwh: 55,
    consumption: 15.8,
    year: 2024,
    rating: 7.8,
    pros: [
      'Affordable entry into VW EV lineup',
      'Good build quality and interior',
      'Compact size ideal for city driving',
      'Excellent dealer network in Germany',
    ],
    cons: [
      'Limited range (350 km real-world)',
      'Slower charging than competitors',
      'Infotainment can be sluggish',
      'Rear visibility limited',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/vw/id3/',
  },
  {
    id: 'vw-id3-pro-2024',
    brand: 'Volkswagen',
    model: 'ID.3',
    variant: 'Pro 58 kWh',
    fuel_type: 'bev',
    power_kw: 150,
    battery_kwh: 58,
    consumption: 15.9,
    year: 2024,
    rating: 8.0,
    pros: [
      'Good balance of price and range',
      'Improved interior with 2024 refresh',
      'Compact size ideal for city driving',
      'Excellent dealer network in Germany',
    ],
    cons: [
      'Charging speed still lags competitors',
      'Infotainment can be sluggish',
      'Rear visibility limited',
      'No frunk storage',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/vw/id3/',
  },
  {
    id: 'vw-id3-pro-s-2024',
    brand: 'Volkswagen',
    model: 'ID.3',
    variant: 'Pro S 79 kWh',
    fuel_type: 'bev',
    power_kw: 170,
    battery_kwh: 79,
    consumption: 16.2,
    year: 2024,
    rating: 8.2,
    pros: [
      'Long range (550+ km WLTP)',
      'Improved interior with 2024 refresh',
      'Comfortable ride quality',
      'Excellent dealer network in Germany',
    ],
    cons: [
      'Price approaches larger EVs',
      'Charging speed still lags competitors',
      'Infotainment can be sluggish',
      'Rear visibility limited',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/vw/id3/',
  },
  {
    id: 'vw-id3-gtx-2024',
    brand: 'Volkswagen',
    model: 'ID.3',
    variant: 'GTX 79 kWh',
    fuel_type: 'bev',
    power_kw: 210,
    battery_kwh: 79,
    consumption: 16.5,
    year: 2024,
    rating: 8.3,
    pros: [
      'Sporty performance (7s 0-100)',
      'Long range with large battery',
      'GTX styling enhancements',
      'Progressive steering and Sport modes',
    ],
    cons: [
      'Expensive for a compact hatch',
      'Still FWD only (no AWD)',
      'Infotainment can be sluggish',
      'Not as quick as hot hatch rivals',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/vw/id3/',
  },
  {
    id: 'vw-id3-gtx-performance-2024',
    brand: 'Volkswagen',
    model: 'ID.3',
    variant: 'GTX Performance 79 kWh',
    fuel_type: 'bev',
    power_kw: 240,
    battery_kwh: 79,
    consumption: 16.8,
    year: 2024,
    rating: 8.4,
    pros: [
      'Hot hatch level performance (5.7s 0-100)',
      'DCC adaptive dampers included',
      'Long range with large battery',
      'GTX styling enhancements',
    ],
    cons: [
      'Expensive for the segment',
      'Still FWD only (no AWD)',
      'Higher energy consumption',
      'Infotainment can be sluggish',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/vw/id3/',
  },

  // VW ID.4
  {
    id: 'vw-id4-pure-2024',
    brand: 'Volkswagen',
    model: 'ID.4',
    variant: 'Pure 55 kWh',
    fuel_type: 'bev',
    power_kw: 125,
    battery_kwh: 55,
    consumption: 16.9,
    year: 2024,
    rating: 7.7,
    pros: [
      'Affordable compact SUV entry',
      'Good build quality',
      'Spacious interior for the class',
      'Excellent dealer network in Germany',
    ],
    cons: [
      'Limited range (340 km real-world)',
      'Slow charging (135 kW max)',
      'Infotainment can be sluggish',
      'Basic feature set at this trim',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/vw/id4/',
  },
  {
    id: 'vw-id4-pro-2024',
    brand: 'Volkswagen',
    model: 'ID.4',
    variant: 'Pro 77 kWh',
    fuel_type: 'bev',
    power_kw: 210,
    battery_kwh: 77,
    consumption: 17.0,
    year: 2024,
    rating: 8.1,
    pros: [
      'Good range (500+ km WLTP)',
      'Spacious and practical interior',
      'Comfortable ride quality',
      'Excellent dealer network in Germany',
    ],
    cons: [
      'Charging speed lags competitors',
      'Infotainment can be sluggish',
      'RWD only at this trim',
      'Styling is conservative',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/vw/id4/',
  },
  {
    id: 'vw-id4-pro-s-2024',
    brand: 'Volkswagen',
    model: 'ID.4',
    variant: 'Pro S 77 kWh',
    fuel_type: 'bev',
    power_kw: 210,
    battery_kwh: 77,
    consumption: 17.2,
    year: 2024,
    rating: 8.2,
    pros: [
      'Well-equipped with premium features',
      'Good range (500+ km WLTP)',
      'Comfortable ride quality',
      'Panoramic roof standard',
    ],
    cons: [
      'Expensive for the segment',
      'Charging speed lags competitors',
      'Infotainment can be sluggish',
      'RWD only at this trim',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/vw/id4/',
  },
  {
    id: 'vw-id4-gtx-2024',
    brand: 'Volkswagen',
    model: 'ID.4',
    variant: 'GTX AWD 77 kWh',
    fuel_type: 'bev',
    power_kw: 250,
    battery_kwh: 77,
    consumption: 18.5,
    year: 2024,
    rating: 8.3,
    pros: [
      'AWD provides excellent traction',
      'Sporty GTX styling and performance',
      'Good range despite AWD',
      'Practical family SUV',
    ],
    cons: [
      'High price point',
      'Higher energy consumption',
      'Charging speed lags competitors',
      'Infotainment can be sluggish',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/vw/id4/',
  },

  // VW ID.5
  {
    id: 'vw-id5-pro-2024',
    brand: 'Volkswagen',
    model: 'ID.5',
    variant: 'Pro 77 kWh',
    fuel_type: 'bev',
    power_kw: 210,
    battery_kwh: 77,
    consumption: 16.3,
    year: 2024,
    rating: 8.2,
    pros: [
      'Sleek coupe-SUV styling',
      'Better efficiency than ID.4',
      'Good range (520+ km WLTP)',
      'Comfortable ride quality',
    ],
    cons: [
      'Reduced rear headroom vs ID.4',
      'Charging speed lags competitors',
      'Premium over ID.4 is significant',
      'Infotainment can be sluggish',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/vw/id5/',
  },
  {
    id: 'vw-id5-pro-s-2024',
    brand: 'Volkswagen',
    model: 'ID.5',
    variant: 'Pro S 77 kWh',
    fuel_type: 'bev',
    power_kw: 210,
    battery_kwh: 77,
    consumption: 16.5,
    year: 2024,
    rating: 8.3,
    pros: [
      'Premium features included',
      'Sleek coupe-SUV styling',
      'Good range (520+ km WLTP)',
      'Panoramic roof standard',
    ],
    cons: [
      'Expensive for the segment',
      'Reduced rear headroom vs ID.4',
      'Charging speed lags competitors',
      'Infotainment can be sluggish',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/vw/id5/',
  },
  {
    id: 'vw-id5-gtx-2024',
    brand: 'Volkswagen',
    model: 'ID.5',
    variant: 'GTX AWD 77 kWh',
    fuel_type: 'bev',
    power_kw: 250,
    battery_kwh: 77,
    consumption: 17.9,
    year: 2024,
    rating: 8.4,
    pros: [
      'AWD with sporty GTX performance',
      'Sleek coupe-SUV styling',
      'Good range despite AWD',
      'Comfortable and practical',
    ],
    cons: [
      'High price point',
      'Reduced rear headroom vs ID.4',
      'Higher energy consumption',
      'Infotainment can be sluggish',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/vw/id5/',
  },

  // VW ID.7
  {
    id: 'vw-id7-pro-2024',
    brand: 'Volkswagen',
    model: 'ID.7',
    variant: 'Pro 77 kWh',
    fuel_type: 'bev',
    power_kw: 210,
    battery_kwh: 77,
    consumption: 14.9,
    year: 2024,
    rating: 8.5,
    pros: [
      'Excellent efficiency for its size',
      'Spacious executive sedan interior',
      'Long range (615 km WLTP)',
      'Refined and comfortable ride',
    ],
    cons: [
      'High starting price',
      'Charging speed still lags best',
      'Infotainment learning curve',
      'Conservative styling',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/vw/id7/',
  },
  {
    id: 'vw-id7-pro-s-2024',
    brand: 'Volkswagen',
    model: 'ID.7',
    variant: 'Pro S 86 kWh',
    fuel_type: 'bev',
    power_kw: 210,
    battery_kwh: 86,
    consumption: 14.1,
    year: 2024,
    rating: 8.7,
    pros: [
      'Impressive 700 km WLTP range',
      'Best efficiency in class',
      'Luxurious interior',
      'Excellent long-distance cruiser',
    ],
    cons: [
      'Premium price point',
      'Charging speed could be better',
      'Infotainment learning curve',
      'RWD only at this trim',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/vw/id7/',
  },
  {
    id: 'vw-id7-gtx-2024',
    brand: 'Volkswagen',
    model: 'ID.7',
    variant: 'GTX AWD 86 kWh',
    fuel_type: 'bev',
    power_kw: 250,
    battery_kwh: 86,
    consumption: 16.2,
    year: 2024,
    rating: 8.6,
    pros: [
      'AWD with sporty GTX performance',
      'Still excellent range (595 km)',
      'Luxurious and spacious',
      'Good handling for its size',
    ],
    cons: [
      'Very expensive',
      'Higher consumption than RWD',
      'Infotainment learning curve',
      'Heavy weight affects dynamics',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/vw/id7/',
  },

  // VW ID. Buzz
  {
    id: 'vw-id-buzz-pro-2024',
    brand: 'Volkswagen',
    model: 'ID. Buzz',
    variant: 'Pro 77 kWh',
    fuel_type: 'bev',
    power_kw: 210,
    battery_kwh: 77,
    consumption: 20.4,
    year: 2024,
    rating: 8.3,
    pros: [
      'Iconic retro design',
      'Extremely spacious interior',
      'Versatile seating configurations',
      'Fun driving character',
    ],
    cons: [
      'High energy consumption',
      'Limited range (400 km real-world)',
      'Very expensive',
      'Slow charging for the price',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/vw/id-buzz/',
  },
  {
    id: 'vw-id-buzz-pro-s-2024',
    brand: 'Volkswagen',
    model: 'ID. Buzz',
    variant: 'Pro S 86 kWh LWB',
    fuel_type: 'bev',
    power_kw: 210,
    battery_kwh: 86,
    consumption: 20.7,
    year: 2024,
    rating: 8.5,
    pros: [
      'Extended wheelbase adds space',
      'Available 7-seat option',
      'Improved range over SWB',
      'Iconic retro design',
    ],
    cons: [
      'Very expensive',
      'High energy consumption',
      'Large footprint for parking',
      'Slow charging for the price',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/vw/id-buzz/',
  },
  {
    id: 'vw-id-buzz-gtx-2024',
    brand: 'Volkswagen',
    model: 'ID. Buzz',
    variant: 'GTX AWD 86 kWh',
    fuel_type: 'bev',
    power_kw: 250,
    battery_kwh: 86,
    consumption: 21.5,
    year: 2024,
    rating: 8.4,
    pros: [
      'AWD for improved traction',
      'Sporty GTX performance',
      'Iconic retro design',
      'Extremely spacious interior',
    ],
    cons: [
      'Premium price tag',
      'Highest energy consumption',
      'Range suffers with AWD',
      'Large footprint for parking',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/vw/id-buzz/',
  },

  // ============================================
  // AUDI
  // ============================================

  // Audi Q4 e-tron
  {
    id: 'audi-q4-etron-35-2024',
    brand: 'Audi',
    model: 'Q4 e-tron',
    variant: '35 52 kWh',
    fuel_type: 'bev',
    power_kw: 125,
    battery_kwh: 52,
    consumption: 17.0,
    year: 2024,
    rating: 7.8,
    pros: [
      'Premium Audi interior quality',
      'Compact SUV practicality',
      'Good build quality',
      'Excellent dealer network',
    ],
    cons: [
      'Limited range (340 km real-world)',
      'Entry model feels underpowered',
      'Slow charging (110 kW max)',
      'Expensive for the range',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/audi/q4-e-tron/',
  },
  {
    id: 'audi-q4-etron-40-2024',
    brand: 'Audi',
    model: 'Q4 e-tron',
    variant: '40 77 kWh',
    fuel_type: 'bev',
    power_kw: 150,
    battery_kwh: 77,
    consumption: 17.3,
    year: 2024,
    rating: 8.1,
    pros: [
      'Good range (500+ km WLTP)',
      'Premium Audi interior',
      'Comfortable ride quality',
      'Efficient RWD drivetrain',
    ],
    cons: [
      'Charging speed lags competitors',
      'RWD only at this trim',
      'Expensive for the segment',
      'Infotainment has learning curve',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/audi/q4-e-tron/',
  },
  {
    id: 'audi-q4-etron-45-2024',
    brand: 'Audi',
    model: 'Q4 e-tron',
    variant: '45 quattro 77 kWh',
    fuel_type: 'bev',
    power_kw: 195,
    battery_kwh: 77,
    consumption: 17.8,
    year: 2024,
    rating: 8.2,
    pros: [
      'quattro AWD system',
      'Premium Audi interior',
      'Good balance of range and power',
      'Comfortable ride quality',
    ],
    cons: [
      'High price for compact SUV',
      'Charging speed lags competitors',
      'Higher consumption than RWD',
      'Some rivals offer more space',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/audi/q4-e-tron/',
  },
  {
    id: 'audi-q4-etron-50-2024',
    brand: 'Audi',
    model: 'Q4 e-tron',
    variant: '50 quattro 77 kWh',
    fuel_type: 'bev',
    power_kw: 220,
    battery_kwh: 77,
    consumption: 18.2,
    year: 2024,
    rating: 8.3,
    pros: [
      'Strongest Q4 e-tron variant',
      'quattro AWD system',
      'Premium Audi interior',
      'Good performance (6.2s 0-100)',
    ],
    cons: [
      'Expensive for compact SUV',
      'Higher consumption',
      'Charging speed lags competitors',
      'Limited real-world range',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/audi/q4-e-tron/',
  },

  // Audi Q6 e-tron
  {
    id: 'audi-q6-etron-2024',
    brand: 'Audi',
    model: 'Q6 e-tron',
    variant: 'Performance 95 kWh',
    fuel_type: 'bev',
    power_kw: 240,
    battery_kwh: 95,
    consumption: 17.0,
    year: 2024,
    rating: 8.6,
    pros: [
      'New PPE platform with 800V architecture',
      'Fast charging (270 kW)',
      'Excellent range (625 km WLTP)',
      'Premium interior with new tech',
    ],
    cons: [
      'High starting price',
      'RWD-only base model',
      'New infotainment needs refinement',
      'Subscription features controversial',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/audi/q6-e-tron/',
  },
  {
    id: 'audi-q6-etron-quattro-2024',
    brand: 'Audi',
    model: 'Q6 e-tron',
    variant: 'quattro 95 kWh',
    fuel_type: 'bev',
    power_kw: 285,
    battery_kwh: 95,
    consumption: 18.2,
    year: 2024,
    rating: 8.7,
    pros: [
      'quattro AWD with excellent traction',
      'Fast charging (270 kW)',
      'Premium Audi quality',
      'Spacious and practical',
    ],
    cons: [
      'Expensive',
      'Higher consumption than RWD',
      'New infotainment needs refinement',
      'Subscription features controversial',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/audi/q6-e-tron/',
  },
  {
    id: 'audi-sq6-etron-2024',
    brand: 'Audi',
    model: 'SQ6 e-tron',
    variant: 'quattro 95 kWh',
    fuel_type: 'bev',
    power_kw: 380,
    battery_kwh: 95,
    consumption: 18.9,
    year: 2024,
    rating: 8.8,
    pros: [
      'Sporty S-model performance',
      'Fast charging (270 kW)',
      'quattro AWD system',
      'Premium interior and features',
    ],
    cons: [
      'Very expensive',
      'Higher energy consumption',
      'Reduced range vs base models',
      'Subscription features controversial',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/audi/q6-e-tron/',
  },

  // Audi Q8 e-tron
  {
    id: 'audi-q8-etron-50-2024',
    brand: 'Audi',
    model: 'Q8 e-tron',
    variant: '50 quattro 95 kWh',
    fuel_type: 'bev',
    power_kw: 250,
    battery_kwh: 95,
    consumption: 22.0,
    year: 2024,
    rating: 8.0,
    pros: [
      'Spacious luxury SUV',
      'Premium interior quality',
      'quattro AWD standard',
      'Comfortable ride',
    ],
    cons: [
      'High energy consumption',
      'Aging platform (MLB evo)',
      'Slower charging than newer EVs',
      'Very expensive',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/audi/q8-e-tron/',
  },
  {
    id: 'audi-q8-etron-55-2024',
    brand: 'Audi',
    model: 'Q8 e-tron',
    variant: '55 quattro 114 kWh',
    fuel_type: 'bev',
    power_kw: 300,
    battery_kwh: 114,
    consumption: 23.5,
    year: 2024,
    rating: 8.2,
    pros: [
      'Excellent range (580+ km WLTP)',
      'Luxurious interior',
      'Strong performance',
      'Comfortable long-distance cruiser',
    ],
    cons: [
      'Very high energy consumption',
      'Aging platform',
      'Slow charging vs newer EVs',
      'Very expensive',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/audi/q8-e-tron/',
  },
  {
    id: 'audi-sq8-etron-2024',
    brand: 'Audi',
    model: 'SQ8 e-tron',
    variant: 'quattro 114 kWh',
    fuel_type: 'bev',
    power_kw: 370,
    battery_kwh: 114,
    consumption: 26.0,
    year: 2024,
    rating: 8.1,
    pros: [
      'Powerful S performance',
      'Luxurious interior',
      'Spacious SUV',
      'Strong road presence',
    ],
    cons: [
      'Extremely high consumption',
      'Very expensive',
      'Aging platform',
      'Limited real-world range',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/audi/q8-e-tron/',
  },

  // Audi e-tron GT
  {
    id: 'audi-etron-gt-2024',
    brand: 'Audi',
    model: 'e-tron GT',
    variant: 'quattro 97 kWh',
    fuel_type: 'bev',
    power_kw: 350,
    battery_kwh: 97,
    consumption: 19.6,
    year: 2024,
    rating: 8.9,
    pros: [
      'Stunning design',
      'Fast 800V charging (270 kW)',
      'Excellent driving dynamics',
      'Premium interior quality',
    ],
    cons: [
      'Very expensive',
      'Limited rear headroom',
      'Small trunk',
      'Range suffers in cold weather',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/audi/e-tron-gt/',
  },
  {
    id: 'audi-rs-etron-gt-2024',
    brand: 'Audi',
    model: 'RS e-tron GT',
    variant: '97 kWh',
    fuel_type: 'bev',
    power_kw: 475,
    battery_kwh: 97,
    consumption: 20.2,
    year: 2024,
    rating: 9.2,
    pros: [
      'Supercar-level performance',
      'Stunning design',
      'Fast 800V charging (270 kW)',
      'Track-capable dynamics',
    ],
    cons: [
      'Extremely expensive',
      'Limited rear headroom',
      'Small trunk',
      'High consumption',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/audi/e-tron-gt/',
  },

  // ============================================
  // BMW
  // ============================================

  // BMW iX1
  {
    id: 'bmw-ix1-edrive20-2024',
    brand: 'BMW',
    model: 'iX1',
    variant: 'eDrive20 65 kWh',
    fuel_type: 'bev',
    power_kw: 150,
    battery_kwh: 65,
    consumption: 16.1,
    year: 2024,
    rating: 8.2,
    pros: [
      'Practical compact SUV size',
      'Premium BMW interior',
      'Good real-world range (~400 km)',
      'Excellent dealer network',
    ],
    cons: [
      'Slow charging (130 kW max)',
      'Premium price for compact SUV',
      'FWD only in base model',
      'Less sporty than ICE X1',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/bmw/ix1/',
  },
  {
    id: 'bmw-ix1-xdrive30-2024',
    brand: 'BMW',
    model: 'iX1',
    variant: 'xDrive30 65 kWh',
    fuel_type: 'bev',
    power_kw: 230,
    battery_kwh: 65,
    consumption: 17.2,
    year: 2024,
    rating: 8.4,
    pros: [
      'xDrive AWD system',
      'Strong performance (5.6s 0-100)',
      'Premium BMW interior',
      'Practical compact SUV',
    ],
    cons: [
      'Expensive for compact SUV',
      'Slow charging (130 kW max)',
      'Higher consumption than eDrive20',
      'Range reduced by AWD',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/bmw/ix1/',
  },

  // BMW iX2
  {
    id: 'bmw-ix2-edrive20-2024',
    brand: 'BMW',
    model: 'iX2',
    variant: 'eDrive20 65 kWh',
    fuel_type: 'bev',
    power_kw: 150,
    battery_kwh: 65,
    consumption: 15.7,
    year: 2024,
    rating: 8.1,
    pros: [
      'Sleek coupe-SUV styling',
      'More efficient than iX1',
      'Premium BMW interior',
      'Good real-world range',
    ],
    cons: [
      'Reduced rear headroom',
      'Slow charging (130 kW max)',
      'Premium price',
      'Less practical than iX1',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/bmw/ix2/',
  },
  {
    id: 'bmw-ix2-xdrive30-2024',
    brand: 'BMW',
    model: 'iX2',
    variant: 'xDrive30 65 kWh',
    fuel_type: 'bev',
    power_kw: 230,
    battery_kwh: 65,
    consumption: 16.7,
    year: 2024,
    rating: 8.3,
    pros: [
      'xDrive AWD system',
      'Strong performance',
      'Sleek coupe-SUV styling',
      'Premium BMW interior',
    ],
    cons: [
      'Expensive',
      'Reduced rear headroom',
      'Slow charging (130 kW max)',
      'Less practical than iX1',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/bmw/ix2/',
  },

  // BMW iX3
  {
    id: 'bmw-ix3-2024',
    brand: 'BMW',
    model: 'iX3',
    variant: '74 kWh',
    fuel_type: 'bev',
    power_kw: 210,
    battery_kwh: 74,
    consumption: 18.5,
    year: 2024,
    rating: 7.9,
    pros: [
      'Familiar X3 practicality',
      'Good range (~450 km)',
      'Premium interior quality',
      'Excellent dealer network',
    ],
    cons: [
      'Aging design (based on G01 X3)',
      'RWD only (no xDrive)',
      'Higher consumption than rivals',
      'Slow charging (150 kW max)',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/bmw/ix3/',
  },

  // BMW i4
  {
    id: 'bmw-i4-edrive35-2024',
    brand: 'BMW',
    model: 'i4',
    variant: 'eDrive35 66 kWh',
    fuel_type: 'bev',
    power_kw: 210,
    battery_kwh: 66,
    consumption: 15.8,
    year: 2024,
    rating: 8.3,
    pros: [
      'Excellent driving dynamics',
      'Gran Coupe practicality',
      'Good efficiency',
      'Premium BMW interior',
    ],
    cons: [
      'Limited range (~400 km)',
      'Slow charging (180 kW max)',
      'Controversial grille design',
      'Smaller battery than competitors',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/bmw/i4/',
  },
  {
    id: 'bmw-i4-edrive40-2024',
    brand: 'BMW',
    model: 'i4',
    variant: 'eDrive40 84 kWh',
    fuel_type: 'bev',
    power_kw: 250,
    battery_kwh: 84,
    consumption: 16.1,
    year: 2024,
    rating: 8.6,
    pros: [
      'Excellent range (590 km WLTP)',
      'Great driving dynamics',
      'Efficient and quick',
      'Premium BMW interior',
    ],
    cons: [
      'Slow charging (205 kW max)',
      'Controversial grille design',
      'RWD only',
      'High price point',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/bmw/i4/',
  },
  {
    id: 'bmw-i4-m50-2024',
    brand: 'BMW',
    model: 'i4',
    variant: 'M50 84 kWh',
    fuel_type: 'bev',
    power_kw: 400,
    battery_kwh: 84,
    consumption: 18.1,
    year: 2024,
    rating: 8.8,
    pros: [
      'M Performance badge deserved',
      'Excellent driving dynamics',
      'AWD xDrive standard',
      'Quick acceleration (3.9s 0-100)',
    ],
    cons: [
      'Expensive',
      'Higher consumption',
      'Slow charging for M car',
      'Controversial grille design',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/bmw/i4/',
  },

  // BMW i5
  {
    id: 'bmw-i5-edrive40-2024',
    brand: 'BMW',
    model: 'i5',
    variant: 'eDrive40 84 kWh',
    fuel_type: 'bev',
    power_kw: 250,
    battery_kwh: 84,
    consumption: 16.5,
    year: 2024,
    rating: 8.5,
    pros: [
      'Luxurious executive sedan',
      'Excellent range (580+ km WLTP)',
      'Premium interior quality',
      'Good driving dynamics',
    ],
    cons: [
      'Very expensive',
      'Slow charging (205 kW max)',
      'Controversial design elements',
      'Heavy weight affects handling',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/bmw/i5/',
  },
  {
    id: 'bmw-i5-m60-2024',
    brand: 'BMW',
    model: 'i5',
    variant: 'M60 xDrive 84 kWh',
    fuel_type: 'bev',
    power_kw: 442,
    battery_kwh: 84,
    consumption: 18.5,
    year: 2024,
    rating: 8.7,
    pros: [
      'M Performance in luxury sedan',
      'Quick acceleration (3.8s 0-100)',
      'AWD xDrive standard',
      'Premium features throughout',
    ],
    cons: [
      'Very expensive',
      'High consumption',
      'Slow charging for the price',
      'Heavy weight',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/bmw/i5/',
  },

  // BMW i7
  {
    id: 'bmw-i7-edrive50-2024',
    brand: 'BMW',
    model: 'i7',
    variant: 'eDrive50 102 kWh',
    fuel_type: 'bev',
    power_kw: 335,
    battery_kwh: 102,
    consumption: 18.4,
    year: 2024,
    rating: 8.6,
    pros: [
      'Ultimate luxury EV sedan',
      'Theatre Screen entertainment',
      'Excellent range (600+ km WLTP)',
      'Whisper-quiet refinement',
    ],
    cons: [
      'Extremely expensive',
      'Polarizing exterior design',
      'Very heavy vehicle',
      'Complex tech can overwhelm',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/bmw/i7/',
  },
  {
    id: 'bmw-i7-xdrive60-2024',
    brand: 'BMW',
    model: 'i7',
    variant: 'xDrive60 102 kWh',
    fuel_type: 'bev',
    power_kw: 400,
    battery_kwh: 102,
    consumption: 19.6,
    year: 2024,
    rating: 8.7,
    pros: [
      'AWD luxury flagship',
      'Strong performance',
      'Theatre Screen entertainment',
      'Excellent range despite AWD',
    ],
    cons: [
      'Extremely expensive',
      'Polarizing exterior design',
      'Very heavy and large',
      'High consumption',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/bmw/i7/',
  },
  {
    id: 'bmw-i7-m70-2024',
    brand: 'BMW',
    model: 'i7',
    variant: 'M70 xDrive 102 kWh',
    fuel_type: 'bev',
    power_kw: 485,
    battery_kwh: 102,
    consumption: 20.5,
    year: 2024,
    rating: 8.9,
    pros: [
      'M Performance luxury flagship',
      'Incredible acceleration (3.7s 0-100)',
      'Ultimate luxury features',
      'Still good range despite power',
    ],
    cons: [
      'Astronomical price',
      'Very high consumption',
      'Extremely heavy',
      'Overkill for most buyers',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/bmw/i7/',
  },

  // BMW iX
  {
    id: 'bmw-ix-xdrive40-2024',
    brand: 'BMW',
    model: 'iX',
    variant: 'xDrive40 77 kWh',
    fuel_type: 'bev',
    power_kw: 240,
    battery_kwh: 77,
    consumption: 19.5,
    year: 2024,
    rating: 8.3,
    pros: [
      'Innovative interior design',
      'Sustainable materials used',
      'Good range (~400 km)',
      'AWD standard',
    ],
    cons: [
      'Polarizing exterior design',
      'High price for range offered',
      'Limited rear visibility',
      'Slower charging than rivals',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/bmw/ix/',
  },
  {
    id: 'bmw-ix-xdrive50-2024',
    brand: 'BMW',
    model: 'iX',
    variant: 'xDrive50 105 kWh',
    fuel_type: 'bev',
    power_kw: 385,
    battery_kwh: 105,
    consumption: 19.8,
    year: 2024,
    rating: 8.6,
    pros: [
      'Excellent range (600+ km WLTP)',
      'Innovative interior design',
      'Strong performance',
      'Fast charging (200 kW)',
    ],
    cons: [
      'Very expensive',
      'Polarizing exterior design',
      'Limited rear visibility',
      'High consumption',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/bmw/ix/',
  },
  {
    id: 'bmw-ix-m60-2024',
    brand: 'BMW',
    model: 'iX',
    variant: 'M60 105 kWh',
    fuel_type: 'bev',
    power_kw: 455,
    battery_kwh: 105,
    consumption: 21.5,
    year: 2024,
    rating: 8.7,
    pros: [
      'M Performance SUV',
      'Incredible acceleration (3.8s 0-100)',
      'Innovative interior',
      'Good range despite power',
    ],
    cons: [
      'Very expensive',
      'Highest consumption in lineup',
      'Polarizing design',
      'Very heavy vehicle',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/bmw/ix/',
  },

  // ============================================
  // HYUNDAI
  // ============================================

  // Hyundai Ioniq 5
  {
    id: 'hyundai-ioniq5-sr-2024',
    brand: 'Hyundai',
    model: 'Ioniq 5',
    variant: 'Standard Range 58 kWh',
    fuel_type: 'bev',
    power_kw: 125,
    battery_kwh: 58,
    consumption: 16.7,
    year: 2024,
    rating: 8.0,
    pros: [
      'Ultra-fast 800V charging (220 kW)',
      'Unique retro-futuristic design',
      'Spacious interior',
      'V2L vehicle-to-load capability',
    ],
    cons: [
      'Limited range (~350 km)',
      'Entry model lacks features',
      'Firm ride quality',
      'Slow RWD performance',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/hyundai/ioniq-5/',
  },
  {
    id: 'hyundai-ioniq5-lr-rwd-2024',
    brand: 'Hyundai',
    model: 'Ioniq 5',
    variant: 'Long Range RWD 77 kWh',
    fuel_type: 'bev',
    power_kw: 168,
    battery_kwh: 77,
    consumption: 16.8,
    year: 2024,
    rating: 8.6,
    pros: [
      'Ultra-fast 800V charging (220 kW)',
      'Good range (500+ km WLTP)',
      'Spacious flat-floor interior',
      'V2L vehicle-to-load capability',
    ],
    cons: [
      'Firm ride quality',
      'Wind noise at highway speeds',
      'RWD only in this trim',
      'Rear visibility limited',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/hyundai/ioniq-5/',
  },
  {
    id: 'hyundai-ioniq5-lr-awd-2024',
    brand: 'Hyundai',
    model: 'Ioniq 5',
    variant: 'Long Range AWD 77 kWh',
    fuel_type: 'bev',
    power_kw: 239,
    battery_kwh: 77,
    consumption: 18.1,
    year: 2024,
    rating: 8.7,
    pros: [
      'Ultra-fast 800V charging (220 kW)',
      'AWD for all-weather traction',
      'Strong performance (5.1s 0-100)',
      'Spacious flat-floor interior',
    ],
    cons: [
      'Higher consumption',
      'Range reduced by AWD',
      'Firm ride quality',
      'Wind noise at highway speeds',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/hyundai/ioniq-5/',
  },
  {
    id: 'hyundai-ioniq5-n-2024',
    brand: 'Hyundai',
    model: 'Ioniq 5 N',
    variant: '84 kWh',
    fuel_type: 'bev',
    power_kw: 478,
    battery_kwh: 84,
    consumption: 21.0,
    year: 2024,
    rating: 9.0,
    pros: [
      'Incredible performance (3.4s 0-100)',
      'N e-shift simulates gearbox',
      'Track-focused driving modes',
      'Most fun EV to drive',
    ],
    cons: [
      'Very expensive',
      'High energy consumption',
      'Limited real-world range',
      'Firm N suspension setup',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/hyundai/ioniq-5-n/',
  },

  // Hyundai Ioniq 6
  {
    id: 'hyundai-ioniq6-sr-2024',
    brand: 'Hyundai',
    model: 'Ioniq 6',
    variant: 'Standard Range 53 kWh',
    fuel_type: 'bev',
    power_kw: 111,
    battery_kwh: 53,
    consumption: 13.9,
    year: 2024,
    rating: 8.0,
    pros: [
      'Excellent efficiency (0.14 Cd)',
      'Ultra-fast 800V charging',
      'Unique streamlined design',
      'Comfortable interior',
    ],
    cons: [
      'Limited range (~400 km)',
      'Slow performance',
      'Reduced rear headroom',
      'Limited trunk space',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/hyundai/ioniq-6/',
  },
  {
    id: 'hyundai-ioniq6-lr-rwd-2024',
    brand: 'Hyundai',
    model: 'Ioniq 6',
    variant: 'Long Range RWD 77 kWh',
    fuel_type: 'bev',
    power_kw: 168,
    battery_kwh: 77,
    consumption: 14.3,
    year: 2024,
    rating: 8.8,
    pros: [
      'Excellent 614 km WLTP range',
      'Ultra-fast 800V charging (220 kW)',
      'World Car of the Year winner',
      'Exceptional efficiency',
    ],
    cons: [
      'Reduced rear headroom',
      'Limited trunk opening',
      'Polarizing design',
      'Less practical than Ioniq 5',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/hyundai/ioniq-6/',
  },
  {
    id: 'hyundai-ioniq6-lr-awd-2024',
    brand: 'Hyundai',
    model: 'Ioniq 6',
    variant: 'Long Range AWD 77 kWh',
    fuel_type: 'bev',
    power_kw: 239,
    battery_kwh: 77,
    consumption: 15.1,
    year: 2024,
    rating: 8.7,
    pros: [
      'AWD traction with good range',
      'Ultra-fast 800V charging',
      'Strong performance (5.1s 0-100)',
      'Still very efficient for AWD',
    ],
    cons: [
      'Reduced rear headroom',
      'Higher price than RWD',
      'Limited trunk opening',
      'Range reduced vs RWD',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/hyundai/ioniq-6/',
  },

  // ============================================
  // KIA
  // ============================================

  // Kia EV6
  {
    id: 'kia-ev6-sr-2024',
    brand: 'Kia',
    model: 'EV6',
    variant: 'Standard Range 58 kWh',
    fuel_type: 'bev',
    power_kw: 125,
    battery_kwh: 58,
    consumption: 16.6,
    year: 2024,
    rating: 8.0,
    pros: [
      'Ultra-fast 800V charging (220 kW)',
      'Sleek crossover design',
      'Good build quality',
      'V2L vehicle-to-load capability',
    ],
    cons: [
      'Limited range (~350 km)',
      'Entry trim lacks features',
      'Tight rear headroom',
      'Slow base performance',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/kia/ev6/',
  },
  {
    id: 'kia-ev6-lr-rwd-2024',
    brand: 'Kia',
    model: 'EV6',
    variant: 'Long Range RWD 77 kWh',
    fuel_type: 'bev',
    power_kw: 168,
    battery_kwh: 77,
    consumption: 16.5,
    year: 2024,
    rating: 8.6,
    pros: [
      'Ultra-fast 800V charging (220 kW)',
      'Good range (528 km WLTP)',
      'Sleek crossover design',
      'V2L vehicle-to-load capability',
    ],
    cons: [
      'RWD only in this trim',
      'Tight rear headroom',
      'Limited cargo space',
      'Piano black interior scratches',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/kia/ev6/',
  },
  {
    id: 'kia-ev6-lr-awd-2024',
    brand: 'Kia',
    model: 'EV6',
    variant: 'Long Range AWD 77 kWh',
    fuel_type: 'bev',
    power_kw: 239,
    battery_kwh: 77,
    consumption: 17.2,
    year: 2024,
    rating: 8.7,
    pros: [
      'AWD traction',
      'Ultra-fast 800V charging',
      'Strong performance (5.2s 0-100)',
      'Good range despite AWD',
    ],
    cons: [
      'Higher price',
      'Tight rear headroom',
      'Range reduced vs RWD',
      'Higher consumption',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/kia/ev6/',
  },
  {
    id: 'kia-ev6-gt-2024',
    brand: 'Kia',
    model: 'EV6',
    variant: 'GT 77 kWh',
    fuel_type: 'bev',
    power_kw: 430,
    battery_kwh: 77,
    consumption: 20.6,
    year: 2024,
    rating: 8.9,
    pros: [
      'Supercar acceleration (3.5s 0-100)',
      'Electronic limited-slip diff',
      'GT-specific suspension',
      'Drift mode function',
    ],
    cons: [
      'Very high consumption',
      'Limited range (~350 km real-world)',
      'Expensive',
      'Firm ride quality',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/kia/ev6/',
  },

  // Kia EV9
  {
    id: 'kia-ev9-lr-rwd-2024',
    brand: 'Kia',
    model: 'EV9',
    variant: 'Long Range RWD 100 kWh',
    fuel_type: 'bev',
    power_kw: 150,
    battery_kwh: 100,
    consumption: 19.8,
    year: 2024,
    rating: 8.4,
    pros: [
      'Spacious 6 or 7 seats',
      'Ultra-fast 800V charging (230 kW)',
      'Striking design',
      'Good range for size (541 km)',
    ],
    cons: [
      'Very large footprint',
      'RWD feels underpowered',
      'High energy consumption',
      'Very expensive',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/kia/ev9/',
  },
  {
    id: 'kia-ev9-lr-awd-2024',
    brand: 'Kia',
    model: 'EV9',
    variant: 'Long Range AWD 100 kWh',
    fuel_type: 'bev',
    power_kw: 283,
    battery_kwh: 100,
    consumption: 22.0,
    year: 2024,
    rating: 8.6,
    pros: [
      'Spacious 6 or 7 seats',
      'AWD for family safety',
      'Ultra-fast 800V charging',
      'Commanding road presence',
    ],
    cons: [
      'Very high consumption',
      'Very large footprint',
      'Expensive',
      'Limited real-world range',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/kia/ev9/',
  },
  {
    id: 'kia-ev9-gt-2024',
    brand: 'Kia',
    model: 'EV9',
    variant: 'GT 100 kWh',
    fuel_type: 'bev',
    power_kw: 384,
    battery_kwh: 100,
    consumption: 23.5,
    year: 2024,
    rating: 8.5,
    pros: [
      'GT performance in family SUV',
      'Quick acceleration (4.3s 0-100)',
      'Spacious 6 or 7 seats',
      'Ultra-fast 800V charging',
    ],
    cons: [
      'Extremely high consumption',
      'Very expensive',
      'Limited real-world range',
      'Very heavy vehicle',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/kia/ev9/',
  },

  // Kia EV3
  {
    id: 'kia-ev3-sr-2024',
    brand: 'Kia',
    model: 'EV3',
    variant: 'Standard Range 58 kWh',
    fuel_type: 'bev',
    power_kw: 150,
    battery_kwh: 58,
    consumption: 15.2,
    year: 2024,
    rating: 8.2,
    pros: [
      'Affordable compact EV',
      'Spacious for its size',
      'Good efficiency',
      '400V charging (128 kW)',
    ],
    cons: [
      'Not 800V like larger siblings',
      'Limited range (~350 km)',
      'Smaller dealer network',
      'Basic interior materials',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/kia/ev3/',
  },
  {
    id: 'kia-ev3-lr-2024',
    brand: 'Kia',
    model: 'EV3',
    variant: 'Long Range 81 kWh',
    fuel_type: 'bev',
    power_kw: 150,
    battery_kwh: 81,
    consumption: 15.5,
    year: 2024,
    rating: 8.5,
    pros: [
      'Excellent range for segment (600 km)',
      'Spacious for a compact',
      'Good efficiency',
      'Competitive pricing',
    ],
    cons: [
      'Not 800V architecture',
      'Slower charging (128 kW)',
      'FWD only',
      'Basic interior materials',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/kia/ev3/',
  },

  // ============================================
  // MG (SAIC)
  // ============================================

  // MG4
  {
    id: 'mg4-standard-2024',
    brand: 'MG',
    model: 'MG4',
    variant: 'Standard 51 kWh',
    fuel_type: 'bev',
    power_kw: 125,
    battery_kwh: 51,
    consumption: 15.8,
    year: 2024,
    rating: 7.8,
    pros: [
      'Excellent value for money',
      'Fun rear-wheel drive dynamics',
      'Good standard equipment',
      '7-year warranty',
    ],
    cons: [
      'Limited range (~300 km)',
      'Slow charging (117 kW max)',
      'Basic interior quality',
      'Limited dealer network',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/mg/mg4/',
  },
  {
    id: 'mg4-long-range-2024',
    brand: 'MG',
    model: 'MG4',
    variant: 'Long Range 64 kWh',
    fuel_type: 'bev',
    power_kw: 150,
    battery_kwh: 64,
    consumption: 16.0,
    year: 2024,
    rating: 8.2,
    pros: [
      'Excellent value for money',
      'Good range (~400 km)',
      'Fun rear-wheel drive dynamics',
      '7-year warranty',
    ],
    cons: [
      'Slow charging (135 kW max)',
      'Basic interior quality',
      'Limited dealer network',
      'Infotainment needs improvement',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/mg/mg4/',
  },
  {
    id: 'mg4-extended-range-2024',
    brand: 'MG',
    model: 'MG4',
    variant: 'Extended Range 77 kWh',
    fuel_type: 'bev',
    power_kw: 180,
    battery_kwh: 77,
    consumption: 16.6,
    year: 2024,
    rating: 8.3,
    pros: [
      'Long range (520 km WLTP)',
      'Still great value',
      'Fun rear-wheel drive dynamics',
      '7-year warranty',
    ],
    cons: [
      'Slow charging (140 kW max)',
      'Basic interior quality',
      'Price approaches premium rivals',
      'Limited dealer network',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/mg/mg4/',
  },
  {
    id: 'mg4-xpower-2024',
    brand: 'MG',
    model: 'MG4',
    variant: 'XPower AWD 64 kWh',
    fuel_type: 'bev',
    power_kw: 320,
    battery_kwh: 64,
    consumption: 17.8,
    year: 2024,
    rating: 8.4,
    pros: [
      'Hot hatch performance (3.8s 0-100)',
      'AWD traction',
      'Excellent value vs rivals',
      '7-year warranty',
    ],
    cons: [
      'Range reduced by AWD (~350 km)',
      'Slow charging (140 kW max)',
      'Interior not up to performance level',
      'Limited dealer network',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/mg/mg4/',
  },

  // MG5
  {
    id: 'mg5-sr-2024',
    brand: 'MG',
    model: 'MG5',
    variant: 'Standard Range 50 kWh',
    fuel_type: 'bev',
    power_kw: 130,
    battery_kwh: 50,
    consumption: 16.5,
    year: 2024,
    rating: 7.6,
    pros: [
      'Only EV estate in segment',
      'Excellent value',
      'Practical wagon body',
      '7-year warranty',
    ],
    cons: [
      'Limited range (~300 km)',
      'Slow charging (87 kW max)',
      'Basic interior quality',
      'Limited dealer network',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/mg/mg5/',
  },
  {
    id: 'mg5-lr-2024',
    brand: 'MG',
    model: 'MG5',
    variant: 'Long Range 61 kWh',
    fuel_type: 'bev',
    power_kw: 156,
    battery_kwh: 61,
    consumption: 17.0,
    year: 2024,
    rating: 7.9,
    pros: [
      'Only EV estate in segment',
      'Good range (~400 km)',
      'Practical cargo space',
      '7-year warranty',
    ],
    cons: [
      'Slow charging (87 kW max)',
      'Basic interior quality',
      'Limited dealer network',
      'Dated infotainment',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/mg/mg5/',
  },

  // MG ZS EV
  {
    id: 'mg-zs-ev-sr-2024',
    brand: 'MG',
    model: 'ZS EV',
    variant: 'Standard Range 51 kWh',
    fuel_type: 'bev',
    power_kw: 130,
    battery_kwh: 51,
    consumption: 17.3,
    year: 2024,
    rating: 7.5,
    pros: [
      'Affordable small SUV',
      'Good standard equipment',
      'Spacious interior',
      '7-year warranty',
    ],
    cons: [
      'Limited range (~300 km)',
      'Slow charging (92 kW max)',
      'Basic interior quality',
      'Dated platform',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/mg/zs/',
  },
  {
    id: 'mg-zs-ev-lr-2024',
    brand: 'MG',
    model: 'ZS EV',
    variant: 'Long Range 72 kWh',
    fuel_type: 'bev',
    power_kw: 156,
    battery_kwh: 72,
    consumption: 17.8,
    year: 2024,
    rating: 7.7,
    pros: [
      'Good range for price (~400 km)',
      'Spacious interior',
      'Good standard equipment',
      '7-year warranty',
    ],
    cons: [
      'Slow charging (92 kW max)',
      'Basic interior quality',
      'Dated platform',
      'Limited dealer network',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/mg/zs/',
  },

  // ============================================
  // POLESTAR
  // ============================================

  // Polestar 2
  {
    id: 'polestar-2-sr-2024',
    brand: 'Polestar',
    model: 'Polestar 2',
    variant: 'Standard Range 69 kWh',
    fuel_type: 'bev',
    power_kw: 200,
    battery_kwh: 69,
    consumption: 15.5,
    year: 2024,
    rating: 8.0,
    pros: [
      'Scandinavian minimalist design',
      'Excellent driving dynamics',
      'Premium interior quality',
      'Good efficiency',
    ],
    cons: [
      'Limited range (~400 km)',
      'Slow charging (135 kW max)',
      'Small dealer network',
      'Tight rear space',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/polestar/polestar-2/',
  },
  {
    id: 'polestar-2-lr-sm-2024',
    brand: 'Polestar',
    model: 'Polestar 2',
    variant: 'Long Range Single Motor 82 kWh',
    fuel_type: 'bev',
    power_kw: 220,
    battery_kwh: 82,
    consumption: 15.2,
    year: 2024,
    rating: 8.4,
    pros: [
      'Excellent range (615 km WLTP)',
      'Best efficiency in lineup',
      'Premium interior quality',
      'Good driving dynamics',
    ],
    cons: [
      'Slow charging (205 kW max)',
      'Small dealer network',
      'Tight rear space',
      'High price for single motor',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/polestar/polestar-2/',
  },
  {
    id: 'polestar-2-lr-dm-2024',
    brand: 'Polestar',
    model: 'Polestar 2',
    variant: 'Long Range Dual Motor 82 kWh',
    fuel_type: 'bev',
    power_kw: 310,
    battery_kwh: 82,
    consumption: 16.5,
    year: 2024,
    rating: 8.5,
    pros: [
      'AWD with good range',
      'Strong performance (4.5s 0-100)',
      'Excellent driving dynamics',
      'Premium interior quality',
    ],
    cons: [
      'Expensive',
      'Slow charging vs rivals',
      'Small dealer network',
      'Tight rear space',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/polestar/polestar-2/',
  },
  {
    id: 'polestar-2-performance-2024',
    brand: 'Polestar',
    model: 'Polestar 2',
    variant: 'Long Range Performance 82 kWh',
    fuel_type: 'bev',
    power_kw: 350,
    battery_kwh: 82,
    consumption: 17.0,
    year: 2024,
    rating: 8.6,
    pros: [
      'Performance pack transforms dynamics',
      'Ohlins dampers included',
      'Quick acceleration (4.2s 0-100)',
      'Brembo brakes',
    ],
    cons: [
      'Very expensive',
      'Firm ride quality',
      'Higher consumption',
      'Small dealer network',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/polestar/polestar-2/',
  },

  // Polestar 3
  {
    id: 'polestar-3-lr-dm-2024',
    brand: 'Polestar',
    model: 'Polestar 3',
    variant: 'Long Range Dual Motor 111 kWh',
    fuel_type: 'bev',
    power_kw: 360,
    battery_kwh: 111,
    consumption: 18.4,
    year: 2024,
    rating: 8.6,
    pros: [
      'Stunning SUV design',
      'Large 111 kWh battery',
      'Fast charging (250 kW)',
      'Premium interior quality',
    ],
    cons: [
      'Very expensive',
      'Limited dealer network',
      'Higher consumption',
      'New model, unproven reliability',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/polestar/polestar-3/',
  },
  {
    id: 'polestar-3-performance-2024',
    brand: 'Polestar',
    model: 'Polestar 3',
    variant: 'Performance 111 kWh',
    fuel_type: 'bev',
    power_kw: 380,
    battery_kwh: 111,
    consumption: 19.0,
    year: 2024,
    rating: 8.7,
    pros: [
      'Performance pack with Ohlins',
      'Stunning SUV design',
      'Fast charging (250 kW)',
      'Premium interior quality',
    ],
    cons: [
      'Very expensive',
      'Firm ride quality',
      'Limited dealer network',
      'High consumption',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/polestar/polestar-3/',
  },

  // Polestar 4
  {
    id: 'polestar-4-lr-sm-2024',
    brand: 'Polestar',
    model: 'Polestar 4',
    variant: 'Long Range Single Motor 102 kWh',
    fuel_type: 'bev',
    power_kw: 200,
    battery_kwh: 102,
    consumption: 15.7,
    year: 2024,
    rating: 8.4,
    pros: [
      'Excellent efficiency',
      'Unique no rear window design',
      'Good range (620 km WLTP)',
      'Fast charging (200 kW)',
    ],
    cons: [
      'No rear window polarizing',
      'Limited dealer network',
      'New model, unproven',
      'High price',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/polestar/polestar-4/',
  },
  {
    id: 'polestar-4-lr-dm-2024',
    brand: 'Polestar',
    model: 'Polestar 4',
    variant: 'Long Range Dual Motor 102 kWh',
    fuel_type: 'bev',
    power_kw: 400,
    battery_kwh: 102,
    consumption: 17.0,
    year: 2024,
    rating: 8.6,
    pros: [
      'Quick acceleration (3.8s 0-100)',
      'AWD traction',
      'Unique design language',
      'Fast charging (200 kW)',
    ],
    cons: [
      'No rear window polarizing',
      'Very expensive',
      'Limited dealer network',
      'Higher consumption',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/polestar/polestar-4/',
  },

  // ============================================
  // SMART
  // ============================================

  // Smart #1
  {
    id: 'smart-1-pro-2024',
    brand: 'Smart',
    model: '#1',
    variant: 'Pro 49 kWh',
    fuel_type: 'bev',
    power_kw: 200,
    battery_kwh: 49,
    consumption: 15.6,
    year: 2024,
    rating: 7.8,
    pros: [
      'Compact premium crossover',
      'Strong performance for size',
      'Modern interior design',
      'Good maneuverability',
    ],
    cons: [
      'Limited range (~310 km)',
      'Small cargo space',
      'Limited dealer network',
      'Some features subscription-based',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/smart/smart-1/',
  },
  {
    id: 'smart-1-premium-2024',
    brand: 'Smart',
    model: '#1',
    variant: 'Premium 66 kWh',
    fuel_type: 'bev',
    power_kw: 200,
    battery_kwh: 66,
    consumption: 16.5,
    year: 2024,
    rating: 8.1,
    pros: [
      'Good range (~420 km WLTP)',
      'Premium interior',
      'Fast charging (150 kW)',
      'Compact city-friendly size',
    ],
    cons: [
      'Expensive for the size',
      'Small cargo space',
      'Limited dealer network',
      'Some features subscription-based',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/smart/smart-1/',
  },
  {
    id: 'smart-1-brabus-2024',
    brand: 'Smart',
    model: '#1',
    variant: 'Brabus 66 kWh',
    fuel_type: 'bev',
    power_kw: 315,
    battery_kwh: 66,
    consumption: 18.0,
    year: 2024,
    rating: 8.3,
    pros: [
      'Hot hatch performance (3.9s 0-100)',
      'Brabus styling and tuning',
      'AWD traction',
      'Unique in segment',
    ],
    cons: [
      'Very expensive for size',
      'High consumption',
      'Reduced range (~350 km)',
      'Small cargo space',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/smart/smart-1/',
  },

  // Smart #3
  {
    id: 'smart-3-pro-2024',
    brand: 'Smart',
    model: '#3',
    variant: 'Pro 49 kWh',
    fuel_type: 'bev',
    power_kw: 200,
    battery_kwh: 49,
    consumption: 15.3,
    year: 2024,
    rating: 7.9,
    pros: [
      'Sleek coupe styling',
      'Strong performance',
      'Modern interior design',
      'More aerodynamic than #1',
    ],
    cons: [
      'Limited range (~320 km)',
      'Less practical than #1',
      'Limited dealer network',
      'Some features subscription-based',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/smart/smart-3/',
  },
  {
    id: 'smart-3-premium-2024',
    brand: 'Smart',
    model: '#3',
    variant: 'Premium 66 kWh',
    fuel_type: 'bev',
    power_kw: 200,
    battery_kwh: 66,
    consumption: 16.0,
    year: 2024,
    rating: 8.2,
    pros: [
      'Good range (~435 km WLTP)',
      'Sleek coupe styling',
      'Fast charging (150 kW)',
      'Premium interior',
    ],
    cons: [
      'Expensive',
      'Less practical than #1',
      'Limited dealer network',
      'Some features subscription-based',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/smart/smart-3/',
  },
  {
    id: 'smart-3-brabus-2024',
    brand: 'Smart',
    model: '#3',
    variant: 'Brabus 66 kWh',
    fuel_type: 'bev',
    power_kw: 315,
    battery_kwh: 66,
    consumption: 17.5,
    year: 2024,
    rating: 8.4,
    pros: [
      'Hot hatch performance (3.7s 0-100)',
      'Sleek Brabus styling',
      'AWD traction',
      'More efficient than #1 Brabus',
    ],
    cons: [
      'Very expensive',
      'Reduced range',
      'Less practical coupe shape',
      'Limited dealer network',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/smart/smart-3/',
  },

  // ============================================
  // CUPRA
  // ============================================

  // Cupra Born
  {
    id: 'cupra-born-45-2024',
    brand: 'Cupra',
    model: 'Born',
    variant: '45 kWh',
    fuel_type: 'bev',
    power_kw: 110,
    battery_kwh: 45,
    consumption: 15.5,
    year: 2024,
    rating: 7.7,
    pros: [
      'Sporty Cupra styling',
      'Good handling dynamics',
      'Affordable entry point',
      'VW group reliability',
    ],
    cons: [
      'Limited range (~310 km)',
      'Slow charging (110 kW max)',
      'Entry model underpowered',
      'Same as VW ID.3 underneath',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/cupra/born/',
  },
  {
    id: 'cupra-born-58-2024',
    brand: 'Cupra',
    model: 'Born',
    variant: '58 kWh',
    fuel_type: 'bev',
    power_kw: 150,
    battery_kwh: 58,
    consumption: 15.8,
    year: 2024,
    rating: 8.0,
    pros: [
      'Good balance of range/price',
      'Sporty Cupra styling',
      'Good handling dynamics',
      'VW group reliability',
    ],
    cons: [
      'Charging still slow (120 kW)',
      'Higher price than ID.3',
      'FWD only',
      'Rear visibility limited',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/cupra/born/',
  },
  {
    id: 'cupra-born-77-2024',
    brand: 'Cupra',
    model: 'Born',
    variant: '77 kWh',
    fuel_type: 'bev',
    power_kw: 170,
    battery_kwh: 77,
    consumption: 16.1,
    year: 2024,
    rating: 8.2,
    pros: [
      'Long range (545 km WLTP)',
      'Sporty Cupra styling',
      'Good handling dynamics',
      'Faster charging (135 kW)',
    ],
    cons: [
      'Expensive for the segment',
      'FWD only',
      'Charging still lags rivals',
      'Premium over ID.3 significant',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/cupra/born/',
  },
  {
    id: 'cupra-born-vz-2024',
    brand: 'Cupra',
    model: 'Born',
    variant: 'VZ 79 kWh',
    fuel_type: 'bev',
    power_kw: 240,
    battery_kwh: 79,
    consumption: 16.8,
    year: 2024,
    rating: 8.4,
    pros: [
      'Hot hatch performance (5.6s 0-100)',
      'DCC adaptive dampers',
      'Long range despite power',
      'Sporty Cupra design',
    ],
    cons: [
      'Expensive',
      'Still FWD only',
      'Charging lags rivals',
      'Some rivals offer AWD',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/cupra/born/',
  },

  // Cupra Tavascan
  {
    id: 'cupra-tavascan-endurance-2024',
    brand: 'Cupra',
    model: 'Tavascan',
    variant: 'Endurance 77 kWh',
    fuel_type: 'bev',
    power_kw: 210,
    battery_kwh: 77,
    consumption: 17.0,
    year: 2024,
    rating: 8.2,
    pros: [
      'Striking coupe-SUV design',
      'Good range (517 km WLTP)',
      'Sporty Cupra character',
      'Premium interior',
    ],
    cons: [
      'Expensive',
      'RWD only in this trim',
      'Charging lags competitors',
      'Reduced rear headroom',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/cupra/tavascan/',
  },
  {
    id: 'cupra-tavascan-vz-2024',
    brand: 'Cupra',
    model: 'Tavascan',
    variant: 'VZ AWD 77 kWh',
    fuel_type: 'bev',
    power_kw: 250,
    battery_kwh: 77,
    consumption: 18.2,
    year: 2024,
    rating: 8.4,
    pros: [
      'AWD with sporty VZ tuning',
      'Striking coupe-SUV design',
      'Good performance (5.5s 0-100)',
      'Premium interior',
    ],
    cons: [
      'Very expensive',
      'Higher consumption',
      'Charging lags competitors',
      'Reduced rear headroom',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/cupra/tavascan/',
  },

  // ============================================
  // NIO
  // ============================================

  // NIO ET5
  {
    id: 'nio-et5-75-2024',
    brand: 'NIO',
    model: 'ET5',
    variant: '75 kWh',
    fuel_type: 'bev',
    power_kw: 360,
    battery_kwh: 75,
    consumption: 17.2,
    year: 2024,
    rating: 8.3,
    pros: [
      'Strong performance (4.3s 0-100)',
      'Battery swap capability',
      'Premium interior quality',
      'Innovative NOMI AI assistant',
    ],
    cons: [
      'Limited range (~400 km)',
      'Small dealer/service network',
      'BaaS adds complexity',
      'Unproven long-term reliability',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/nio/et5/',
  },
  {
    id: 'nio-et5-100-2024',
    brand: 'NIO',
    model: 'ET5',
    variant: '100 kWh',
    fuel_type: 'bev',
    power_kw: 360,
    battery_kwh: 100,
    consumption: 17.5,
    year: 2024,
    rating: 8.5,
    pros: [
      'Excellent range (580+ km)',
      'Battery swap capability',
      'Strong performance',
      'Premium interior quality',
    ],
    cons: [
      'Expensive with 100 kWh battery',
      'Small dealer/service network',
      'BaaS adds complexity',
      'Unproven long-term reliability',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/nio/et5/',
  },

  // NIO ET5 Touring
  {
    id: 'nio-et5-touring-75-2024',
    brand: 'NIO',
    model: 'ET5 Touring',
    variant: '75 kWh',
    fuel_type: 'bev',
    power_kw: 360,
    battery_kwh: 75,
    consumption: 17.8,
    year: 2024,
    rating: 8.4,
    pros: [
      'Sleek estate/wagon body',
      'Battery swap capability',
      'Strong performance',
      'Premium interior quality',
    ],
    cons: [
      'Limited range (~390 km)',
      'Small dealer/service network',
      'BaaS adds complexity',
      'Unproven long-term reliability',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/nio/et5-touring/',
  },
  {
    id: 'nio-et5-touring-100-2024',
    brand: 'NIO',
    model: 'ET5 Touring',
    variant: '100 kWh',
    fuel_type: 'bev',
    power_kw: 360,
    battery_kwh: 100,
    consumption: 18.0,
    year: 2024,
    rating: 8.6,
    pros: [
      'Practical estate with good range',
      'Battery swap capability',
      'Strong performance',
      'Premium interior quality',
    ],
    cons: [
      'Expensive with 100 kWh battery',
      'Small dealer/service network',
      'BaaS adds complexity',
      'Unproven long-term reliability',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/nio/et5-touring/',
  },

  // NIO ET7
  {
    id: 'nio-et7-75-2024',
    brand: 'NIO',
    model: 'ET7',
    variant: '75 kWh',
    fuel_type: 'bev',
    power_kw: 480,
    battery_kwh: 75,
    consumption: 18.5,
    year: 2024,
    rating: 8.4,
    pros: [
      'Luxury sedan performance',
      'Battery swap capability',
      'NOMI AI assistant',
      'Premium interior materials',
    ],
    cons: [
      'Limited range (~400 km)',
      'Small dealer/service network',
      'Very expensive',
      'High consumption',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/nio/et7/',
  },
  {
    id: 'nio-et7-100-2024',
    brand: 'NIO',
    model: 'ET7',
    variant: '100 kWh',
    fuel_type: 'bev',
    power_kw: 480,
    battery_kwh: 100,
    consumption: 19.0,
    year: 2024,
    rating: 8.6,
    pros: [
      'Good range for luxury sedan (580 km)',
      'Battery swap capability',
      'Strong performance (3.8s 0-100)',
      'Premium interior quality',
    ],
    cons: [
      'Very expensive',
      'Small dealer/service network',
      'High consumption',
      'BaaS adds complexity',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/nio/et7/',
  },

  // NIO EL6
  {
    id: 'nio-el6-75-2024',
    brand: 'NIO',
    model: 'EL6',
    variant: '75 kWh',
    fuel_type: 'bev',
    power_kw: 360,
    battery_kwh: 75,
    consumption: 19.2,
    year: 2024,
    rating: 8.2,
    pros: [
      'Practical mid-size SUV',
      'Battery swap capability',
      'Strong performance',
      'NOMI AI assistant',
    ],
    cons: [
      'Limited range (~380 km)',
      'High consumption',
      'Small dealer/service network',
      'Unproven long-term reliability',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/nio/el6/',
  },
  {
    id: 'nio-el6-100-2024',
    brand: 'NIO',
    model: 'EL6',
    variant: '100 kWh',
    fuel_type: 'bev',
    power_kw: 360,
    battery_kwh: 100,
    consumption: 19.5,
    year: 2024,
    rating: 8.4,
    pros: [
      'Good range for SUV (530 km)',
      'Battery swap capability',
      'Practical mid-size SUV',
      'Premium interior quality',
    ],
    cons: [
      'Expensive with 100 kWh battery',
      'High consumption',
      'Small dealer/service network',
      'BaaS adds complexity',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/nio/el6/',
  },

  // NIO EL7
  {
    id: 'nio-el7-75-2024',
    brand: 'NIO',
    model: 'EL7',
    variant: '75 kWh',
    fuel_type: 'bev',
    power_kw: 480,
    battery_kwh: 75,
    consumption: 20.5,
    year: 2024,
    rating: 8.1,
    pros: [
      'Large luxury SUV',
      'Battery swap capability',
      'Strong performance (3.9s 0-100)',
      'NOMI AI assistant',
    ],
    cons: [
      'Limited range (~360 km)',
      'Very high consumption',
      'Small dealer/service network',
      'Very expensive',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/nio/el7/',
  },
  {
    id: 'nio-el7-100-2024',
    brand: 'NIO',
    model: 'EL7',
    variant: '100 kWh',
    fuel_type: 'bev',
    power_kw: 480,
    battery_kwh: 100,
    consumption: 21.0,
    year: 2024,
    rating: 8.3,
    pros: [
      'Good range for large SUV (500 km)',
      'Battery swap capability',
      'Strong performance',
      'Premium interior quality',
    ],
    cons: [
      'Very expensive',
      'Very high consumption',
      'Small dealer/service network',
      'BaaS adds complexity',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/nio/el7/',
  },

  // ============================================
  // XPENG
  // ============================================

  // XPeng G6
  {
    id: 'xpeng-g6-sr-2024',
    brand: 'XPeng',
    model: 'G6',
    variant: 'Standard Range 66 kWh',
    fuel_type: 'bev',
    power_kw: 190,
    battery_kwh: 66,
    consumption: 15.0,
    year: 2024,
    rating: 8.0,
    pros: [
      'Excellent efficiency',
      '800V fast charging (280 kW)',
      'Advanced ADAS features',
      'Good value for features',
    ],
    cons: [
      'Limited range (~400 km)',
      'Small dealer network',
      'Unproven reliability',
      'Software needs refinement',
    ],
    reviewUrl: 'https://www.efahrer.com/auto/xpeng-g6/',
  },
  {
    id: 'xpeng-g6-lr-2024',
    brand: 'XPeng',
    model: 'G6',
    variant: 'Long Range 87 kWh',
    fuel_type: 'bev',
    power_kw: 190,
    battery_kwh: 87,
    consumption: 15.5,
    year: 2024,
    rating: 8.4,
    pros: [
      'Excellent range (570 km WLTP)',
      '800V fast charging (280 kW)',
      'Advanced ADAS features',
      'Good efficiency',
    ],
    cons: [
      'Small dealer network',
      'Unproven reliability',
      'Software needs refinement',
      'RWD only in this trim',
    ],
    reviewUrl: 'https://www.efahrer.com/auto/xpeng-g6/',
  },
  {
    id: 'xpeng-g6-awd-2024',
    brand: 'XPeng',
    model: 'G6',
    variant: 'AWD 87 kWh',
    fuel_type: 'bev',
    power_kw: 350,
    battery_kwh: 87,
    consumption: 17.0,
    year: 2024,
    rating: 8.5,
    pros: [
      'Strong AWD performance (4.1s 0-100)',
      '800V fast charging (280 kW)',
      'Advanced ADAS features',
      'Good range despite AWD',
    ],
    cons: [
      'Higher consumption',
      'Small dealer network',
      'Unproven reliability',
      'Software needs refinement',
    ],
    reviewUrl: 'https://www.efahrer.com/auto/xpeng-g6/',
  },

  // XPeng G9
  {
    id: 'xpeng-g9-rwd-2024',
    brand: 'XPeng',
    model: 'G9',
    variant: 'RWD 78 kWh',
    fuel_type: 'bev',
    power_kw: 230,
    battery_kwh: 78,
    consumption: 18.5,
    year: 2024,
    rating: 8.1,
    pros: [
      'Spacious luxury SUV',
      '800V fast charging',
      'Advanced ADAS features',
      'Good performance',
    ],
    cons: [
      'Limited range (~420 km)',
      'Small dealer network',
      'High consumption',
      'Unproven reliability',
    ],
    reviewUrl: 'https://www.efahrer.com/auto/xpeng-g9/',
  },
  {
    id: 'xpeng-g9-awd-2024',
    brand: 'XPeng',
    model: 'G9',
    variant: 'AWD 98 kWh',
    fuel_type: 'bev',
    power_kw: 405,
    battery_kwh: 98,
    consumption: 19.5,
    year: 2024,
    rating: 8.4,
    pros: [
      'Strong AWD performance',
      'Good range (570 km WLTP)',
      '800V fast charging',
      'Spacious luxury SUV',
    ],
    cons: [
      'Expensive',
      'Small dealer network',
      'High consumption',
      'Unproven reliability',
    ],
    reviewUrl: 'https://www.efahrer.com/auto/xpeng-g9/',
  },

  // XPeng P7
  {
    id: 'xpeng-p7-2024',
    brand: 'XPeng',
    model: 'P7',
    variant: 'RWD 86 kWh',
    fuel_type: 'bev',
    power_kw: 196,
    battery_kwh: 86,
    consumption: 15.0,
    year: 2024,
    rating: 8.2,
    pros: [
      'Excellent efficiency',
      'Sleek sedan design',
      'Good range (576 km WLTP)',
      'Advanced ADAS features',
    ],
    cons: [
      'Small dealer network',
      'Unproven reliability',
      'Software needs refinement',
      'Slower charging than G6',
    ],
    reviewUrl: 'https://www.efahrer.com/auto/xpeng-p7/',
  },

  // ============================================
  // ZEEKR
  // ============================================

  // Zeekr 001
  {
    id: 'zeekr-001-86-2024',
    brand: 'Zeekr',
    model: '001',
    variant: 'Long Range 86 kWh',
    fuel_type: 'bev',
    power_kw: 200,
    battery_kwh: 86,
    consumption: 17.5,
    year: 2024,
    rating: 8.3,
    pros: [
      'Unique shooting brake design',
      'Good range (580 km WLTP)',
      'Fast charging',
      'Premium Geely platform',
    ],
    cons: [
      'Limited dealer network',
      'Brand awareness low',
      'Unproven reliability',
      'Software needs refinement',
    ],
    reviewUrl: 'https://www.efahrer.com/auto/zeekr-001/',
  },
  {
    id: 'zeekr-001-100-2024',
    brand: 'Zeekr',
    model: '001',
    variant: 'Performance 100 kWh',
    fuel_type: 'bev',
    power_kw: 400,
    battery_kwh: 100,
    consumption: 19.0,
    year: 2024,
    rating: 8.6,
    pros: [
      'Strong performance (3.8s 0-100)',
      'Excellent range (620 km WLTP)',
      'Unique shooting brake design',
      'Fast charging (200 kW)',
    ],
    cons: [
      'Expensive',
      'Limited dealer network',
      'Unproven reliability',
      'Higher consumption',
    ],
    reviewUrl: 'https://www.efahrer.com/auto/zeekr-001/',
  },

  // Zeekr X
  {
    id: 'zeekr-x-rwd-2024',
    brand: 'Zeekr',
    model: 'X',
    variant: 'RWD 66 kWh',
    fuel_type: 'bev',
    power_kw: 200,
    battery_kwh: 66,
    consumption: 16.0,
    year: 2024,
    rating: 8.1,
    pros: [
      'Compact premium crossover',
      'Good range (~440 km)',
      'Fast charging',
      'Modern interior design',
    ],
    cons: [
      'Limited dealer network',
      'Brand awareness low',
      'Small cargo space',
      'Unproven reliability',
    ],
    reviewUrl: 'https://www.efahrer.com/auto/zeekr-x/',
  },
  {
    id: 'zeekr-x-awd-2024',
    brand: 'Zeekr',
    model: 'X',
    variant: 'AWD 66 kWh',
    fuel_type: 'bev',
    power_kw: 315,
    battery_kwh: 66,
    consumption: 17.5,
    year: 2024,
    rating: 8.3,
    pros: [
      'Strong AWD performance (3.7s 0-100)',
      'Compact premium crossover',
      'Fast charging',
      'Modern interior design',
    ],
    cons: [
      'Reduced range (~380 km)',
      'Limited dealer network',
      'Small cargo space',
      'Unproven reliability',
    ],
    reviewUrl: 'https://www.efahrer.com/auto/zeekr-x/',
  },

  // ============================================
  // BYD
  // ============================================

  // BYD Atto 3
  {
    id: 'byd-atto-3-2024',
    brand: 'BYD',
    model: 'Atto 3',
    variant: '60.5 kWh',
    fuel_type: 'bev',
    power_kw: 150,
    battery_kwh: 60.5,
    consumption: 18.5,
    year: 2024,
    rating: 8.0,
    pros: [
      'Excellent value for money',
      'Spacious interior with rotating screen',
      '5-star Euro NCAP safety rating',
      'Good real-world range (~350km)',
    ],
    cons: [
      'Limited dealer network in Germany',
      'Infotainment takes time to learn',
      'No frunk storage',
      'Average charging speed (88kW max)',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/byd/atto-3/',
  },
  {
    id: 'byd-atto-3-2025',
    brand: 'BYD',
    model: 'Atto 3',
    variant: '60.5 kWh (MY25)',
    fuel_type: 'bev',
    power_kw: 150,
    battery_kwh: 60.5,
    consumption: 18.3,
    year: 2025,
    rating: 8.1,
    pros: [
      'Updated for 2025 model year',
      'Excellent value for money',
      'Spacious interior',
      '5-star Euro NCAP safety rating',
    ],
    cons: [
      'Limited dealer network in Germany',
      'Still average charging speed',
      'No frunk storage',
      'Infotainment learning curve',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/byd/atto-3/',
  },

  // BYD Atto 2 (coming 2025)
  {
    id: 'byd-atto-2-2025',
    brand: 'BYD',
    model: 'Atto 2',
    variant: '45.1 kWh',
    fuel_type: 'bev',
    power_kw: 130,
    battery_kwh: 45.1,
    consumption: 15.6,
    year: 2025,
    rating: 7.8,
    pros: [
      'Affordable entry to BYD range',
      'Good efficiency',
      'Compact city-friendly size',
      'BYD Blade Battery technology',
    ],
    cons: [
      'Limited range (~300 km)',
      'New model, unproven',
      'Limited dealer network',
      'Basic feature set expected',
    ],
    reviewUrl: 'https://www.efahrer.com/auto/byd-atto-2/',
  },

  // BYD Dolphin
  {
    id: 'byd-dolphin-active-2024',
    brand: 'BYD',
    model: 'Dolphin',
    variant: 'Active 44.9 kWh',
    fuel_type: 'bev',
    power_kw: 70,
    battery_kwh: 44.9,
    consumption: 15.9,
    year: 2024,
    rating: 7.6,
    pros: [
      'Affordable entry-level EV',
      'Good efficiency',
      'Funky design',
      'BYD Blade Battery technology',
    ],
    cons: [
      'Slow performance (70 kW)',
      'Limited range (~300 km)',
      'Slow charging (60 kW max)',
      'Basic interior materials',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/byd/dolphin/',
  },
  {
    id: 'byd-dolphin-comfort-2024',
    brand: 'BYD',
    model: 'Dolphin',
    variant: 'Comfort 60.4 kWh',
    fuel_type: 'bev',
    power_kw: 150,
    battery_kwh: 60.4,
    consumption: 17.0,
    year: 2024,
    rating: 8.1,
    pros: [
      'Good range (~400 km)',
      'Strong performance for segment',
      'Good value for money',
      'Funky design',
    ],
    cons: [
      'Slow charging (88 kW max)',
      'Limited dealer network',
      'Higher consumption than rivals',
      'Infotainment learning curve',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/byd/dolphin/',
  },
  {
    id: 'byd-dolphin-design-2024',
    brand: 'BYD',
    model: 'Dolphin',
    variant: 'Design 60.4 kWh',
    fuel_type: 'bev',
    power_kw: 150,
    battery_kwh: 60.4,
    consumption: 17.0,
    year: 2024,
    rating: 8.2,
    pros: [
      'Well-equipped top trim',
      'Good range (~400 km)',
      'Strong performance',
      'Premium features for price',
    ],
    cons: [
      'Slow charging (88 kW max)',
      'Price approaches larger cars',
      'Limited dealer network',
      'Higher consumption than rivals',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/byd/dolphin/',
  },

  // BYD Seal
  {
    id: 'byd-seal-dynamic-2024',
    brand: 'BYD',
    model: 'Seal',
    variant: 'Dynamic RWD 61.4 kWh',
    fuel_type: 'bev',
    power_kw: 150,
    battery_kwh: 61.4,
    consumption: 16.3,
    year: 2024,
    rating: 8.1,
    pros: [
      'Sleek sedan design',
      'Good efficiency',
      'Cell-to-body technology',
      'Good value vs Tesla Model 3',
    ],
    cons: [
      'Limited range (~400 km)',
      'Slow charging (110 kW max)',
      'Limited dealer network',
      'Entry model underpowered',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/byd/seal/',
  },
  {
    id: 'byd-seal-design-2024',
    brand: 'BYD',
    model: 'Seal',
    variant: 'Design RWD 82.6 kWh',
    fuel_type: 'bev',
    power_kw: 230,
    battery_kwh: 82.6,
    consumption: 17.5,
    year: 2024,
    rating: 8.5,
    pros: [
      'Good range (570 km WLTP)',
      'Strong performance',
      'Cell-to-body technology',
      'Excellent value vs competitors',
    ],
    cons: [
      'Charging still slow (150 kW)',
      'Limited dealer network',
      'RWD only in this trim',
      'Infotainment learning curve',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/byd/seal/',
  },
  {
    id: 'byd-seal-excellence-2024',
    brand: 'BYD',
    model: 'Seal',
    variant: 'Excellence AWD 82.6 kWh',
    fuel_type: 'bev',
    power_kw: 390,
    battery_kwh: 82.6,
    consumption: 19.2,
    year: 2024,
    rating: 8.6,
    pros: [
      'Strong AWD performance (3.8s 0-100)',
      'Good range (520 km WLTP)',
      'Excellent value for performance',
      'Cell-to-body technology',
    ],
    cons: [
      'Higher consumption',
      'Charging still slower than 800V',
      'Limited dealer network',
      'Infotainment learning curve',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/byd/seal/',
  },

  // BYD Seal U
  {
    id: 'byd-seal-u-comfort-2024',
    brand: 'BYD',
    model: 'Seal U',
    variant: 'Comfort 71.8 kWh',
    fuel_type: 'bev',
    power_kw: 160,
    battery_kwh: 71.8,
    consumption: 18.0,
    year: 2024,
    rating: 8.0,
    pros: [
      'Spacious family SUV',
      'Good value for size',
      'BYD Blade Battery',
      'Good range (~420 km)',
    ],
    cons: [
      'Slow charging (88 kW max)',
      'Limited dealer network',
      'Entry motor feels slow',
      'Higher consumption',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/byd/seal-u/',
  },
  {
    id: 'byd-seal-u-design-2024',
    brand: 'BYD',
    model: 'Seal U',
    variant: 'Design 87 kWh',
    fuel_type: 'bev',
    power_kw: 160,
    battery_kwh: 87.0,
    consumption: 18.5,
    year: 2024,
    rating: 8.2,
    pros: [
      'Long range (500 km WLTP)',
      'Spacious family SUV',
      'Well-equipped',
      'Good value for size',
    ],
    cons: [
      'Slow charging (115 kW max)',
      'Limited dealer network',
      'Same motor as smaller battery',
      'Higher consumption',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/byd/seal-u/',
  },

  // BYD Sealion 7
  {
    id: 'byd-sealion-7-comfort-2024',
    brand: 'BYD',
    model: 'Sealion 7',
    variant: 'Comfort RWD 82.5 kWh',
    fuel_type: 'bev',
    power_kw: 230,
    battery_kwh: 82.5,
    consumption: 17.8,
    year: 2024,
    rating: 8.3,
    pros: [
      'Tesla Model Y competitor',
      'Good range (502 km WLTP)',
      'Sleek coupe-SUV design',
      'Good value proposition',
    ],
    cons: [
      'Limited dealer network',
      'Charging slower than rivals',
      'New model, unproven',
      'RWD only in this trim',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/byd/sealion-7/',
  },
  {
    id: 'byd-sealion-7-design-2024',
    brand: 'BYD',
    model: 'Sealion 7',
    variant: 'Design AWD 82.5 kWh',
    fuel_type: 'bev',
    power_kw: 390,
    battery_kwh: 82.5,
    consumption: 19.4,
    year: 2024,
    rating: 8.5,
    pros: [
      'Strong AWD performance (4.5s 0-100)',
      'Sleek coupe-SUV design',
      'Good range (456 km WLTP)',
      'Good value vs competitors',
    ],
    cons: [
      'Higher consumption',
      'Limited dealer network',
      'Charging slower than 800V rivals',
      'New model, unproven',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/byd/sealion-7/',
  },
  {
    id: 'byd-sealion-7-excellence-2024',
    brand: 'BYD',
    model: 'Sealion 7',
    variant: 'Excellence AWD 91.3 kWh',
    fuel_type: 'bev',
    power_kw: 390,
    battery_kwh: 91.3,
    consumption: 19.8,
    year: 2024,
    rating: 8.6,
    pros: [
      'Best range in Sealion 7 lineup',
      'Strong AWD performance',
      'Premium features',
      'Sleek coupe-SUV design',
    ],
    cons: [
      'Expensive for BYD',
      'Higher consumption',
      'Limited dealer network',
      'Charging slower than 800V rivals',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/byd/sealion-7/',
  },

  // BYD Tang (SUV)
  {
    id: 'byd-tang-2024',
    brand: 'BYD',
    model: 'Tang',
    variant: 'AWD 86.4 kWh',
    fuel_type: 'bev',
    power_kw: 380,
    battery_kwh: 86.4,
    consumption: 21.5,
    year: 2024,
    rating: 7.8,
    pros: [
      'Large 7-seat SUV',
      'Strong AWD performance',
      'Blade Battery safety',
      'Good equipment level',
    ],
    cons: [
      'High energy consumption',
      'Limited range (~400 km real-world)',
      'Older design',
      'Limited dealer network',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/byd/tang/',
  },

  // BYD Han
  {
    id: 'byd-han-2024',
    brand: 'BYD',
    model: 'Han',
    variant: '85.4 kWh',
    fuel_type: 'bev',
    power_kw: 380,
    battery_kwh: 85.4,
    consumption: 19.5,
    year: 2024,
    rating: 8.1,
    pros: [
      'Luxury sedan positioning',
      'Strong performance (3.9s 0-100)',
      'Good range (~520 km WLTP)',
      'Premium interior',
    ],
    cons: [
      'Limited dealer network',
      'Slow charging (120 kW max)',
      'Higher consumption',
      'Brand perception in Germany',
    ],
    reviewUrl: 'https://www.adac.de/rund-ums-fahrzeug/autokatalog/marken-modelle/byd/han/',
  },
]

// Group presets by brand and model for easier navigation
export function getPresetsByBrand(): Record<string, EVPreset[]> {
  return EV_PRESETS.reduce((acc, preset) => {
    if (!acc[preset.brand]) {
      acc[preset.brand] = []
    }
    acc[preset.brand].push(preset)
    return acc
  }, {} as Record<string, EVPreset[]>)
}

// Search presets by query
export function searchPresets(query: string): EVPreset[] {
  const lowerQuery = query.toLowerCase()
  return EV_PRESETS.filter(
    (preset) =>
      preset.brand.toLowerCase().includes(lowerQuery) ||
      preset.model.toLowerCase().includes(lowerQuery) ||
      preset.variant.toLowerCase().includes(lowerQuery)
  )
}

// Get preset by ID
export function getPresetById(id: string): EVPreset | undefined {
  return EV_PRESETS.find((preset) => preset.id === id)
}

// Find a matching preset for a saved car by brand and model
export function findPresetForCar(car: {
  brand: string
  model: string
}): EVPreset | undefined {
  return EV_PRESETS.find(
    (p) =>
      p.brand.toLowerCase() === car.brand.toLowerCase() &&
      p.model.toLowerCase() === car.model.toLowerCase()
  )
}
