import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { formatCurrency, formatNumber } from './calculations'
import type { Car, Offer } from '@/types/database'
import type { TCOResult } from './calculations'

interface ComparisonItem {
  name: string
  shortName: string
  tco: TCOResult
  offer: Offer
  car: Car
  contractYears: number
  effectiveYears: number
  costPerMonth: number
}

export function exportComparisonToPDF(
  comparisonData: ComparisonItem[],
  years: number,
  compareByContract: boolean
) {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()

  // Title
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text('DRIVENEX Car Comparison', pageWidth / 2, 20, { align: 'center' })

  // Subtitle with date
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(
    `Generated on ${new Date().toLocaleDateString('de-DE')}`,
    pageWidth / 2,
    28,
    { align: 'center' }
  )

  // Comparison mode info
  doc.setFontSize(11)
  doc.text(
    compareByContract
      ? 'Comparison Mode: By Contract Length'
      : `Comparison Mode: Fixed Period (${years} years)`,
    14,
    40
  )

  // Summary section
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('Summary', 14, 52)

  // Summary table
  const summaryData = comparisonData.map((item, index) => [
    index === 0 ? '* Best' : `#${index + 1}`,
    `${item.car.brand} ${item.car.model}`,
    item.offer.name,
    item.offer.type.charAt(0).toUpperCase() + item.offer.type.slice(1),
    `${item.offer.duration_months} mo`,
    formatCurrency(item.tco.totalCost),
    formatCurrency(item.costPerMonth),
  ])

  autoTable(doc, {
    startY: 56,
    head: [['Rank', 'Car', 'Offer', 'Type', 'Duration', 'Total Cost', 'Cost/Month']],
    body: summaryData,
    headStyles: {
      fillColor: [79, 70, 229], // Indigo-600
      textColor: 255,
      fontStyle: 'bold',
    },
    alternateRowStyles: {
      fillColor: [249, 250, 251], // Gray-50
    },
    columnStyles: {
      0: { cellWidth: 15 },
      5: { halign: 'right' },
      6: { halign: 'right' },
    },
  })

  // Detailed breakdown for each offer
  let yPosition = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 15

  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('Cost Breakdown', 14, yPosition)
  yPosition += 6

  const breakdownData = comparisonData.map((item) => {
    const yearly = item.tco.yearlyCosts[0] || {
      monthlyPayment: 0,
      fuelCost: 0,
      insurance: 0,
      tax: 0,
      maintenance: 0,
      tires: 0,
      tuv: 0,
      otherCosts: 0,
    }
    return [
      item.shortName,
      formatCurrency(item.offer.monthly_payment),
      formatCurrency(item.offer.down_payment),
      formatCurrency(item.offer.transfer_fee),
      formatCurrency(yearly.fuelCost),
      formatCurrency(yearly.insurance),
      formatCurrency(yearly.maintenance),
    ]
  })

  autoTable(doc, {
    startY: yPosition,
    head: [['Offer', 'Monthly', 'Down Payment', 'Transfer Fee', 'Fuel/yr', 'Insurance/yr', 'Maint./yr']],
    body: breakdownData,
    headStyles: {
      fillColor: [79, 70, 229],
      textColor: 255,
      fontStyle: 'bold',
      fontSize: 9,
    },
    bodyStyles: {
      fontSize: 9,
    },
    alternateRowStyles: {
      fillColor: [249, 250, 251],
    },
    columnStyles: {
      1: { halign: 'right' },
      2: { halign: 'right' },
      3: { halign: 'right' },
      4: { halign: 'right' },
      5: { halign: 'right' },
      6: { halign: 'right' },
    },
  })

  // Included services section
  yPosition = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 15

  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('Included Services', 14, yPosition)
  yPosition += 6

  const servicesData = comparisonData.map((item) => [
    item.shortName,
    item.offer.includes_insurance ? 'Yes' : 'No',
    item.offer.includes_maintenance ? 'Yes' : 'No',
    item.offer.includes_tax ? 'Yes' : 'No',
    item.offer.includes_tires ? 'Yes' : 'No',
    formatNumber(item.offer.km_per_year),
  ])

  autoTable(doc, {
    startY: yPosition,
    head: [['Offer', 'Insurance', 'Maintenance', 'Tax', 'Tires', 'km/year']],
    body: servicesData,
    headStyles: {
      fillColor: [79, 70, 229],
      textColor: 255,
      fontStyle: 'bold',
    },
    alternateRowStyles: {
      fillColor: [249, 250, 251],
    },
  })

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight()
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(150)
  doc.text(
    'Generated by DRIVENEX - Car Comparison Tool',
    pageWidth / 2,
    pageHeight - 10,
    { align: 'center' }
  )

  // Save the PDF
  const fileName = `drivenex-comparison-${new Date().toISOString().split('T')[0]}.pdf`
  doc.save(fileName)
}
